# Generated by Django 6.0.1 on 2026-01-31 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtlasUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Atlas User',
                'verbose_name_plural': 'Atlas Users',
                'db_table': 'atlas_user',
                'managed': True,
            },
        ),
    ]
