# Generated by Django 6.0.1 on 2026-02-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'atlas_permission',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='atlasuser',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atlasuser',
            name='role',
            field=models.CharField(
                choices=[('researcher', 'Researcher'), ('guest', 'Guest'), ('student', 'Student')],
                default='guest',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='atlasuser',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.permission'),
        ),
    ]
