# Generated by Django 5.1.4 on 2026-02-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_add_notification_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="tag",
            field=models.CharField(
                choices=[
                    ("info", "Info"),
                    ("warning", "Warning"),
                    ("success", "Success"),
                    ("danger", "Danger"),
                ],
                default="info",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="tag",
            field=models.CharField(
                choices=[
                    ("info", "Info"),
                    ("warning", "Warning"),
                    ("success", "Success"),
                    ("danger", "Danger"),
                ],
                default="info",
                max_length=20,
            ),
        ),
    ]
