# Generated by Django 6.0.1 on 2026-02-04 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_permission_atlasuser_is_disabled_atlasuser_role_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "prefix",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mr", "Mr."),
                            ("mrs", "Mrs."),
                            ("ms", "Ms."),
                            ("dr", "Dr."),
                            ("prof", "Prof."),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="accounts.atlasuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "db_table": "atlas_user_profile",
                "managed": True,
            },
        ),
    ]
