# Generated by Django 5.1.4 on 2026-02-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_message_tag_notification_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="target_users",
            field=models.ManyToManyField(
                blank=True, related_name="messages_targeted", to="accounts.user"
            ),
        ),
    ]
