# Generated by Django 6.0.1 on 2026-02-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_permissions_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='external_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
