# Generated by Django 6.0.1 on 2026-02-04 13:51

import bcrypt
from django.db import migrations, models


def seed_admin_user(apps, schema_editor):
    AdminUser = apps.get_model("accounts", "AdminUser")
    email = "akwuru.david@ul.ie"
    if AdminUser.objects.filter(email__iexact=email).exists():
        return
    salt = bcrypt.gensalt(rounds=10, prefix=b"2a")
    hashed_password = bcrypt.hashpw(b"Dayboy20@me", salt).decode("utf-8")
    AdminUser.objects.create(
        name="David Akwuru",
        email=email,
        password=hashed_password,
        affiliation="",
        is_admin=False,
        is_super_admin=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("affiliation", models.CharField(blank=True, max_length=255)),
                ("is_admin", models.BooleanField(default=True)),
                ("is_super_admin", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Admin User",
                "verbose_name_plural": "Admin Users",
                "db_table": "atlas_admin_user",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="affiliation",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(seed_admin_user, migrations.RunPython.noop),
    ]
