# Generated by Django 6.0.1 on 2026-02-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_atlasuser_userprofile_timestamps"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
